### ISSUE TITLE
Some search queries in the search bar returns Playback Error

### ISSUE THREAD

**Issue by SezerYardim** [Seneral/FlagPlayer#10]
I searched for the channel named "travelcomic". I dont really know why it occurs but it treats that keyword as it is a video and returns **"Playback Error: Playability Status: ERROR: Video Unavailable"**

**Comment by NeuroCPP** [comment]
@Seneral i want to learn JS is ....eloquent js book good
https://www.learn-js.org/ and this too
@Sezer-dev he will look into it and as your name suggests you can also contribute
:)
as always
NeuroCPP

**Comment by SezerYardim** [comment]
I think it is about the regular expression inside `ct_navSearch` function.

**Comment by Seneral** [comment]
Yeah it is, with the intention that you can enter ids, though that is not acceptable when it prevents searches.
Would make sense to remove that completely, as you can enter all types of links instead.
If you do want to contribute (as #9 suggests), feel free to do so!
Else I'll do it soon

**Comment by SezerYardim** [comment]
@Seneral I'll do it.
