### ISSUE TITLE
Comments have started to vanish

### ISSUE THREAD

**Issue by NeuroCPP** [Seneral/FlagPlayer#16]
![image](https://user-images.githubusercontent.com/85978957/169736234-fc0e8b2a-ad2a-4954-b1cf-2874085ed047.png)

**Comment by NeuroCPP** [comment]
> ![image](https://user-images.githubusercontent.com/85978957/169736234-fc0e8b2a-ad2a-4954-b1cf-2874085ed047.png)

Top comment and new comments option seem to be intact 
just comments are not loading

**Comment by NeuroCPP** [comment]
Quick Update
![image](https://user-images.githubusercontent.com/85978957/169736523-e480f391-44c3-4557-8599-96f92f9a7eec.png)
now on the same track it shows no comments
....
![image](https://user-images.githubusercontent.com/85978957/169736661-c97c1ece-421c-4c37-919b-873b9c1e0e69.png)
on youtube it shows 3000+ comments

**Comment by Seneral** [comment]
Yep, known issue, just no time to fix
Maybe its a very easy fix

Generally this happens when youtube changes something slightly

Will take a quick look later but no promises

**Comment by NeuroCPP** [comment]
just marking this as an issue..any passerby can help with this
and yep I knew that it might be due to youtube changing their UI (a LOT) recently

**Comment by pacman2108** [comment]
maybe we'll need a newer comments api for this?

**Comment by NeuroCPP** [comment]
> maybe we'll need a newer comments api for this?

oh yes, that can be the most probable issue
as u might have seen that there has been some changes going on there

**Comment by Seneral** [comment]
I'll look into this now, especially because on mobile, related videos are also broken, and I do miss these a lot

**Comment by NeuroCPP** [comment]
> I'll look into this now, especially because on mobile, related videos are also broken, and I do miss these a lot

so should I publish a new issue or edit this one?

**Comment by Seneral** [comment]
Nah it's alright, very related, just usual maintenance.
Desktop stuff all works again, now onto mobile

**Comment by Seneral** [comment]
Fixed in 02543ba and bd83144 respectively!
Will likely break again in the future, but will try to be faster next time.
