### ISSUE TITLE
Let's make the installation of local CORS server on android(linux based thingy) easier..

### ISSUE THREAD

**Issue by NeuroCPP** [Seneral/FlagPlayer#17]
it was not easy for me coz i don't know very much about linux or not at all

**Comment by pacman2108** [comment]
You might want to use termux on Android for the process...

**Comment by pacman2108** [comment]
Process:
`pkg install nodejs`
``cd server && ./CorsServer.sh``
``http://localhost:26060``

**Comment by NeuroCPP** [comment]
> it was not easy for me coz i don't know very much about linux or not at all

No it  was quite easy

> You might want to use termux on Android for the process...

Already using that ,but for different purpose(s)

right now Using d/node.js for running CORS

 Reason: 
- it's easy to setup
- bunch of startup options
- and a GUI 
- and don't have to start it all the time
