### ISSUE TITLE
Public CORS Server down

### ISSUE THREAD

**Issue by Seneral** [Seneral/FlagPlayer#23]
So heroku stopped their free tier of dynamos and also deleted my free credits I had left so the CORS server is down for now.
I am investigating some alternatives, if you have any ideas besides hosting it myself (which I'd do in the worst case) or paying 5€/month, please share them here.

**Comment by NeuroCPP** [comment]
vercel can be good option 
someone else suggested to me for this same project some time back

**Comment by Seneral** [comment]
Ok so finally got a server for another project and set the CORS server up there.
Unfortunately it already has problems despite working at the beginning. Since I was working on other stuff it is not inconceivable that I already got rate-limited. Let's see if it will settle.
Here's the new public cors host, an update should set it automatically (or suggest to replace it):
https://flagplayer-cors.seneral.dev/
While it is still down, this public cors host is also a possibility (though as with all public cors hosts, comments don't load, they require custom handling):
https://proxy.cors.sh/

So for desktop use, please continue to use a local server. I recommend to set it up with a script that starts the server with the web app, and closes it with the web app, so that it looks and behaves like any normal program.
For me on linux it looks like this:
```
#!/bin/sh

cd /path/to/FlagPlayer/server
export HOST=localhost
export PORT=26060
node --max-http-header-size=65536 yt-server.js &
export SERVER_PID=$!

echo "Node Server PID: " $SERVER_PID
# If using chromium binary
#/usr/bin/chromium --profile-directory=Default --app-id=bfnegiddnbgkelpklhkmpgihhpfgobjm
# If using a flatpak, e.g. UngoogledChromium
flatpak 'run' '--command=/app/bin/chromium' 'com.github.Eloston.UngoogledChromium' '--profile-directory=Default' '--app-id=bfnegiddnbgkelpklhkmpgihhpfgobjm'

kill $SERVER_PID
```

**Comment by Seneral** [comment]
Couldn't resolve it, restarted server, it works now. Issue was no outgoing connections worked, ingoing did, not triggered by anything I did afaik. So I'll see if it pops up again

**Comment by NeuroCPP** [comment]
> https://flagplayer-cors.seneral.dev/

this CORS is pretty fast

**Comment by NeuroCPP** [comment]
i did try using vercel but i didn't know nothing ,what to do 😅

**Comment by Seneral** [comment]
> i did try using vercel but i didn't know nothing ,what to do sweat_smile

Yeah it's quite a lot to get into, also to secure it properly.

> > https://flagplayer-cors.seneral.dev/
> 
> this CORS is pretty fast

Compared to the heroku hobby dyno I used before, maybe. That one was free and shut down after half an hour, so the first request took a while. Before THAT I used free github credits for I think nearly 2 years so it was also fast.

**Comment by Seneral** [comment]
Been solid so far so I'll close this
